import type { Metadata } from "next";
import { Figtree, Inter, Plus_Jakarta_Sans } from "next/font/google";
import Provider from "../provider";
import DemoSelector from "../components/demo-selector";
import { cn } from "../lib/utils";

const mainFont = Figtree({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(mainFont.className, "bg-neutral-900 w-svw min-h-svh")}>
        <Provider>
          <DemoSelector />
          <div className="mt-16">
            {children}
          </div>
        </Provider>
      </body>
    </html>
  );
}
