import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import { cn } from "./lib/utils";
import { Toaster } from "sonner";

const mainFont = Figtree({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(mainFont.className, "bg-neutral-900 w-svw min-h-svh")}>
        {children}
      </body>
    </html>
  );
}
